module 2 task 1
js-tasks-ru/jsbasic-20201214_itiszella pull request #3
Opened 2020-12-22 14:28 UTC by itiszella

2020-12-22 14:42 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-12-22 15:14 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Функция sumSalary(salaries)
+ должна игнорировать свойства других типов
+ должна возвращать 0 если нет свойств с зарплатами
+ должна складывать все зарплаты
+ должна игнорировать специальные числовые значения
```
```diff
Определите, пуст ли объект
+ если у объекта есть хоть одно свойство, то он не пустой
+ {} должен вернуть true
+ объект со свойством undefined должен считаться не пустым
+ объект с удалённым свойством - пустой
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2020-12-22 15:55 UTC, SinimaWath requested changes

2020-12-22 15:55 UTC, SinimaWath commented on 2-module/1-task/index.js
> +       delete salaries[key];
Удаление излишне:
1. Изменяешь исходный обьект, а не копию.
2. Это не требуют по условию задачи

2020-12-22 15:55 UTC, SinimaWath commented on 2-module/1-task/index.js
> +    } else if (typeof salaries[key] === 'number') {
Давай перепишем в один if:
```
if (isNumber) {
  sum += salaries[key];
}
```

2020-12-22 15:55 UTC, SinimaWath commented on 2-module/1-task/index.js
> +    if (isNaN(salaries[key]) || salaries[key] == Infinity || salaries[key] == -Infinity) {
Для такой проверки, если функция получше:` isFinite`

2020-12-23 11:51 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Функция sumSalary(salaries)
+ должна возвращать 0 если нет свойств с зарплатами
+ должна игнорировать свойства других типов
+ должна игнорировать специальные числовые значения
+ должна складывать все зарплаты
```
```diff
Определите, пуст ли объект
+ если у объекта есть хоть одно свойство, то он не пустой
+ объект со свойством undefined должен считаться не пустым
+ объект с удалённым свойством - пустой
+ {} должен вернуть true
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2020-12-23 13:24 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Функция sumSalary(salaries)
+ должна игнорировать свойства других типов
+ должна игнорировать специальные числовые значения
+ должна возвращать 0 если нет свойств с зарплатами
+ должна складывать все зарплаты
```
```diff
Определите, пуст ли объект
+ если у объекта есть хоть одно свойство, то он не пустой
+ {} должен вернуть true
+ объект с удалённым свойством - пустой
+ объект со свойством undefined должен считаться не пустым
```
```diff
Создайте калькулятор
+ должно складывать числа
+ должно умножать числа
```

Добавляю преподавателя (@SinimaWath) для код-ревью, посмотрим что он скажет :)

2020-12-23 14:17 UTC, SinimaWath commented on 2-module/1-task/index.js
> +  let clone = Object.assign({}, salaries);
Тут на самом деле, это излешне, но не критично:
1. Функция sumSalary не изменяет исходный обьект.
2. Функция не возвращает новый обьект, на основание входного обькта. А только суммирует.

Когда нужно клонировать:
Когда собираешься изменять исходный обьект: добавлять свойства, изменять, удалять.

Когда только читаешь свойства, не стоит копировать просто так

2020-12-23 14:18 UTC, SinimaWath requested changes

2020-12-23 14:18 UTC, SinimaWath commented on 2-module/1-task/index.js
> +  }
Беда с отступами:
```
for () {
  if (...) {
    ...
  }
}
```

2020-12-23 14:41 UTC, SinimaWath approved these changes

2020-12-23 14:41 UTC, merged